# Generated by Django 3.2.5 on 2021-08-28 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210828_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time_of_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
